### ISSUE TITLE
tilt and pan should be public

### ISSUE THREAD

**Issue by jeremydouglass** [jrc03c/queasycam#3]
In order to calculate facing direction (e.g. to render held objects in front of the camera, throw, shoot, etc.) the QueasyCam class needs to make pan and tilt public. They are currently marked private, so nothing can be known about the player view -- only the player position.

**Comment by jrc03c** [comment]
Okay, I made the requested variables (as well as a few others) public. I also made it easy to get the "facing" direction you mentioned by simply calling for `getForward()`. See the [README](https://github.com/jrc03c/queasycam) for more info about the updated API. Thanks for the suggestions!

**Comment by jeremydouglass** [comment]
Wow -- thank you very much!
