### ISSUE TITLE
Need help with Queasy Cam Positioning

### ISSUE THREAD

**Issue by krhobeck** [jrc03c/queasycam#6]
I have this code here:

import queasycam.*;
float x = 0;
 float y = 0.5; 
float z = 0;
QueasyCam cam;

void setup() 
{ 
  size(1390, 1000, P3D); 
cam = new QueasyCam(this); 
cam.speed = 3; 
cam.sensitivity = 1; 
cam.position = new PVector(x, y, z);
} 
void Gravity() 
{ 
if (cam.position(x, y>1.5, z));
 { 
y -= 1; 
} 
} 
void Ground() 
{ box(1000, 0.5, 1000); } 
void draw() 
{ 
background(0); 
Ground(); 
}

And I am trying to make it so that when you jump the QueasyCam's position will go to a certain point and then drop you back down to create a gravity-like effect. I can make the jump but the gravity is what I am struggling with. PVectors is somewhat confusing to me and I am wondering why this will not work.

**Comment by jrc03c** [comment]
If the following explanation doesn't help, then I'd check out the Maze Runner example that ships with QueasyCam and/or Dan Shiffman's excellent [Nature of Code](http://natureofcode.com/book/) tutorials.

In Processing, vectors can be added in two ways. The first way changes the vector that calls the `.add()` function. For example:

    PVector u = new PVector(1, 2, 3);
    PVector v = new PVector(4, 5, 6);
    u.add(v); 
    // vector u now has a value of <5, 7, 9>, 
    // and vector v is unchanged

The second way changes neither of the original vectors and is accomplished by calling the `.add()` function from the PVector class. (In other words, by calling a static function.) For example:

    PVector u = new PVector(1, 2, 3);
    PVector v = new PVector(4, 5, 6);
    PVector w = PVector.add(u, v);
    // vector w now has a value of <5, 7, 9>, 
    // and vectors u and v are unchanged

I'll use the first way of adding vectors in the code below.

Velocity is a change in position (over a certain amount of time). So, if you want to move the camera in a straight line along, for example, the _x_-axis, then you'd do something like this.

    import queasycam.*;
    
    QueasyCam cam;
    PVector velocity;

    void setup(){
        size(600, 600, P3D);
        cam = new QueasyCam(this);
        velocity = new PVector(1, 0, 0);
    }

    void draw(){
        background(200);
        cam.position.add(velocity);
    }

You won't be able to see much going on in that example, but the camera will be moving. The `cam.position.add(velocity)` is the important part.

Finally, if a velocity is a change in position (over a certain amount of time), then an acceleration is a change in velocity (over a certain amount of time). Gravity, loosely speaking, is an acceleration. In the last example I gave, we changed the camera's position each frame by adding the velocity to the position. To make the camera fall, we need to change the _velocity_ each frame by adding gravity. So, for example:

    import queasycam.*;
    
    QueasyCam cam;
    PVector velocity;
    PVector gravity;

    void setup(){
        size(600, 600, P3D);
        cam = new QueasyCam(this);
        velocity = new PVector(1, 0, 0);
        gravity = new PVector(0, 0.1, 0);
    }

    void draw(){
        background(200);
        velocity.add(gravity);
        cam.position.add(velocity);
    }

**Comment by krhobeck** [comment]
Thanks for the info! Will I have to add PVectors to make the camera not fall through the floor?

**Comment by krhobeck** [comment]
Some final questions before I sign off to go make a 3D world to impress everyone.

I somewhat understand how you were able to recreate gravity with PVectors. Although, if I want to create boundaries for blocks so that you won't float through space how would I do that? I looked into the code you directed me to (Maze Runner) and saw this:

void update(){
    float playerLeft = player.position.x - player.dimensions.x/2;
    float playerRight = player.position.x + player.dimensions.x/2;
    float playerTop = player.position.y - player.dimensions.y/2;
    float playerBottom = player.position.y + player.dimensions.y/2;
    float playerFront = player.position.z - player.dimensions.z/2;
    float playerBack = player.position.z + player.dimensions.z/2;
    
    float boxLeft = position.x - dimensions.x/2;
    float boxRight = position.x + dimensions.x/2;
    float boxTop = position.y - dimensions.y/2;
    float boxBottom = position.y + dimensions.y/2;
    float boxFront = position.z - dimensions.z/2;
    float boxBack = position.z + dimensions.z/2;
    
    float boxLeftOverlap = playerRight - boxLeft;
    float boxRightOverlap = boxRight - playerLeft;
    float boxTopOverlap = playerBottom - boxTop;
    float boxBottomOverlap = boxBottom - playerTop;
    float boxFrontOverlap = playerBack - boxFront;
    float boxBackOverlap = boxBack - playerFront;
    
    if (((playerLeft > boxLeft && playerLeft < boxRight || (playerRight > boxLeft && playerRight < boxRight)) && ((playerTop > boxTop && playerTop < boxBottom) || (playerBottom > boxTop && playerBottom < boxBottom)) && ((playerFront > boxFront && playerFront < boxBack) || (playerBack > boxFront && playerBack < boxBack)))){
      float xOverlap = max(min(boxLeftOverlap, boxRightOverlap), 0);
      float yOverlap = max(min(boxTopOverlap, boxBottomOverlap), 0);
      float zOverlap = max(min(boxFrontOverlap, boxBackOverlap), 0);
      
      if (xOverlap < yOverlap && xOverlap < zOverlap){
        if (boxLeftOverlap < boxRightOverlap){
          player.position.x = boxLeft - player.dimensions.x/2;
        } else {
          player.position.x = boxRight + player.dimensions.x/2;
        }
      }
      
      else if (yOverlap < xOverlap && yOverlap < zOverlap){
        if (boxTopOverlap < boxBottomOverlap){
          player.position.y = boxTop - player.dimensions.y/2;
          player.velocity.y = 0;
          player.grounded = true;
        } else {
          player.position.y = boxBottom + player.dimensions.y/2;
        }
      }
      
      else if (zOverlap < xOverlap && zOverlap < yOverlap){
        if (boxFrontOverlap < boxBackOverlap){
          player.position.z = boxFront - player.dimensions.x/2;
        } else {
          player.position.z = boxBack + player.dimensions.x/2;
        }
      }
    }
  }

From what I understand this is code that checks if the person is next to the box to make sure you don't go through it. Is there a simpler way of doing this? How can I recreate this without using classes? Why do we have to use PVectors to use the camera?

Im thinking I have to track the dimensions of the box like this script does so it would look something like this:

if (position.x>boxsize+boxposition)
{
  velocity.x -= 1
}

Would this be correct?

**Comment by jrc03c** [comment]
Well, I actually did collision checking in the maze runner example in a really simple, hacky way. But proper collision detection is somewhat complex. I'd recommend letting a 3D physics library handle collisions, especially if you're planning on giving the camera or other game objects complex bodies (i.e., more complex than mere cubes). A possible 3D physics library is [toxiclibs](http://toxiclibs.org/about/).

**Comment by krhobeck** [comment]
I am trying to accomplish making a forest with a night sky. Im thinking of making one tree than spreading that across a green rectangle on the ground and maybe some mountains surrounding it. Its for a class project. Not really interested in making a fully fledged game just yet. Again, Thank you for the tips and information, maybe I can rewrite the detection code you made for the Maze Runner?

**Comment by jrc03c** [comment]
Yeah, rewriting the Maze Runner is a fine idea.
